Package is running as emqtt user

diff --git a/bin/emqttd b/bin/emqttd
--- a/bin/emqttd
+++ b/bin/emqttd
@@ -25,6 +25,7 @@ RUNNER_LOG_DIR={{ runner_log_dir }}
 RUNNER_LIB_DIR={{ runner_lib_dir }}
 RUNNER_ETC_DIR={{ runner_etc_dir }}
 RUNNER_DATA_DIR={{ runner_data_dir }}
+RUNNER_USER=emqtt
 
 WHOAMI=$(whoami)
 
@@ -172,6 +173,43 @@ replace_env_in_conf() {
     [ "x" = "x$EMQ_WSS_PORT" ]        || $SED_REPLACE "s/^[ \t]*listener.wss.external[ \t]*=.*$/listener.wss.external = $EMQ_WSS_PORT/" $APPCONF
 }
 
+# Call bootstrapd for daemon commands like start/stop/console
+bootstrapd() {
+    # Fail fast if they have no rights to mess around with pids
+    check_user_internal
+
+    # Make sure the user running this script is the owner and/or su to that user
+    check_user $@
+    ES=$?
+    if [ "$ES" -ne 0 ]; then
+        exit $ES
+    fi
+}
+
+# Simple way to check the correct user and fail early
+check_user_internal() {
+    # Validate that the user running the script is the owner of the
+    # RUN_DIR.
+    if ([ "$RUNNER_USER" ] && [ "x$WHOAMI" != "x$RUNNER_USER" ]); then
+        if [ "x$WHOAMI" != "xroot" ]; then
+            echo "You need to be root or use sudo to run this command"
+            exit 1
+        fi
+    fi
+}
+
+# Function to su into correct user that is poorly named for historical
+check_user() {
+    check_user_internal
+    # do not su again if we are already the runner user
+    if ([ "$RUNNER_USER" ] && [ "x$WHOAMI" != "x$RUNNER_USER" ]); then
+        ESCAPED_ARGS=`echo "$@" | sed -e 's/\([{}"]\)/\\\\\1/g'`
+        # This will drop priviledges into the runner user
+        # It exec's in a new shell and the current shell will exit
+        exec su - $RUNNER_USER -c "$SCRIPT_DIR/emqttd $ESCAPED_ARGS"
+    fi
+}
+
 # Make sure log directory exists
 mkdir -p "$RUNNER_LOG_DIR"
 
@@ -249,6 +287,9 @@ case "$1" in
             echo "Node is already running!"
             exit 1
         fi
+        # Bootstrap daemon command (check perms & drop to $RUNNER_USER)
+        bootstrapd $@
+
         # Save this for later.
         CMD=$1
         case "$1" in
@@ -349,6 +390,9 @@ case "$1" in
             exit 1
         fi
 
+        # Bootstrap daemon command (check perms & drop to $RUNNER_USER)
+        bootstrapd $@
+
         shift
         exec "$BINDIR/to_erl" "$PIPE_DIR"
         ;;
@@ -359,6 +403,9 @@ case "$1" in
             echo "Node is not running!"
             exit 1
         fi
+
+        # Bootstrap daemon command (check perms & drop to $RUNNER_USER)
+        bootstrapd $@
 
         shift
         relx_rem_sh
@@ -401,6 +448,9 @@ case "$1" in
         ;;
 
     console|console_clean|console_boot)
+        # Bootstrap daemon command (check perms & drop to $RUNNER_USER)
+        bootstrapd $@
+
         # .boot file typically just $REL_NAME (ie, the app name)
         # however, for debugging, sometimes start_clean.boot is useful.
         # For e.g. 'setup', one may even want to name another boot script.
@@ -455,6 +505,8 @@ case "$1" in
         ;;
 
     foreground)
+        # Bootstrap daemon command (check perms & drop to $RUNNER_USER)
+        bootstrapd $@
         # start up the release in the foreground for use by runit
         # or other supervision services
 
