Check if the node is already running, and wait for startup

diff --git a/bin/emqttd b/bin/emqttd
--- a/bin/emqttd
+++ b/bin/emqttd
@@ -237,13 +237,11 @@ esac
 # Check the first argument for instructions
 case "$1" in
     start|start_boot)
-
-        # Make sure there is not already a node running
-        #RES=`$NODETOOL ping`
-        #if [ "$RES" = "pong" ]; then
-        #    echo "Node is already running!"
-        #    exit 1
-        #fi
+        # Make sure a node IS not running
+        if relx_nodetool "ping" >/dev/null 2>&1; then
+            echo "Node is already running!"
+            exit 1
+        fi
         # Save this for later.
         CMD=$1
         case "$1" in
@@ -272,6 +270,22 @@ case "$1" in
 
         "$BINDIR/run_erl" -daemon "$PIPE_DIR" "$RUNNER_LOG_DIR" \
                           "$(relx_start_command)"
+
+        WAIT=${WAIT_FOR_ERLANG:-15}
+        while [ $WAIT -gt 0 ]; do
+            WAIT=`expr $WAIT - 1`
+            sleep 1
+            if ! relx_nodetool "ping" >/dev/null 2>&1; then
+                continue
+            fi
+            echo "EMQ-2.0 is started successfully!"
+            exit 0
+        done
+        echo "The EMQ broker failed to start within ${WAIT_FOR_ERLANG:-15} seconds,"
+        echo "see the output of './bin/emqttd console' for more information."
+        echo "If you want to wait longer, set the environment variable"
+        echo "WAIT_FOR_ERLANG to the number of seconds to wait."
+        exit 1
         ;;
 
     stop)
