Improve the release process

diff --git a/bin/emqttd b/bin/emqttd
--- a/bin/emqttd
+++ b/bin/emqttd
@@ -13,12 +13,14 @@ RELEASE_ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd -P)"
 REL_NAME="emqttd"
 REL_VSN="{{ rel_vsn }}"
 ERTS_VSN="{{ erts_vsn }}"
+ERTS_PATH=$RELEASE_ROOT_DIR/erts-$ERTS_VSN/bin
 CODE_LOADING_MODE="${CODE_LOADING_MODE:-embedded}"
 REL_DIR="$RELEASE_ROOT_DIR/releases/$REL_VSN"
 ERL_OPTS="{{ erl_opts }}"
-RUNNER_LOG_DIR="${RUNNER_LOG_DIR:-$RELEASE_ROOT_DIR/log}"
-RUNNER_ETC_DIR="${RUNNER_ETC_DIR:-$RELEASE_ROOT_DIR/etc}"
-RUNNER_DATA_DIR="${RUNNER_DATA_DIR:-$RELEASE_ROOT_DIR/data}"
+RUNNER_LOG_DIR=$RELEASE_ROOT_DIR/log
+RUNNER_LIB_DIR=$RELEASE_ROOT_DIR/lib
+RUNNER_ETC_DIR=$RELEASE_ROOT_DIR/etc
+RUNNER_DATA_DIR=$RELEASE_ROOT_DIR/data
 
 # Warn the user if ulimit -n is less than 1024
 ULIMIT_F=`ulimit -n`
@@ -26,6 +28,17 @@ if [ "$ULIMIT_F" -lt 1024 ]; then
     echo "!!!!"
     echo "!!!! WARNING: ulimit -n is ${ULIMIT_F}; 1024 is the recommended minimum."
     echo "!!!!"
+fi
+
+# Echo to stderr on errors
+echoerr() { echo "$@" 1>&2; }
+
+# Cuttlefish to generate app.config and vm.args
+CUTTLEFISH="on"
+if [ -z "$CUTTLEFISH" ]; then
+    CUTTLEFISH_COMMAND_PREFIX=""
+else
+    CUTTLEFISH_COMMAND_PREFIX="$ERTS_PATH/escript $SCRIPT_DIR/cuttlefish -s $REL_DIR/schema -d $RUNNER_DATA_DIR/configs"
 fi
 
 find_erts_dir() {
@@ -101,70 +114,51 @@ relx_start_command() {
            "$START_OPTION"
 }
 
-# Use $CWD/vm.args if exists, otherwise releases/VSN/vm.args
-if [ -z "$VMARGS_PATH" ]; then
-    if [ -f "$RELEASE_ROOT_DIR/vm.args" ]; then
-        VMARGS_PATH="$RELEASE_ROOT_DIR/vm.args"
+# Function to generate app.config and vm.args
+generate_config() {
+    if [ -z "$CUTTLEFISH" ]; then
+        # Note: we have added a parameter '-vm_args' to this. It
+        # appears redundant but it is not! the erlang vm allows us to
+        # access all arguments to the erl command EXCEPT '-args_file',
+        # so in order to get access to this file location from within
+        # the vm, we need to pass it in twice.
+        CONFIG_ARGS=" -config $RUNNER_ETC_DIR/app.config -args_file $RUNNER_ETC_DIR/vm.args -vm_args $RUNNER_ETC_DIR/vm.args "
     else
-        VMARGS_PATH="$REL_DIR/vm.args"
+        APPCONF=`relx_nodetool mergeconf $RUNNER_ETC_DIR $RUNNER_ETC_DIR/plugins $RUNNER_DATA_DIR/configs`
+        if [ "$?" -ne 0 ]; then
+            echoerr "Error merging configs!"
+            exit 1
+        fi
+        CONFIG_ARGS=`$CUTTLEFISH_COMMAND_PREFIX -c $APPCONF generate`
+        if [ "$?" -ne 0 ]; then
+            echoerr "Error generating config with cuttlefish"
+            echoerr "  run \`$RUNNER_SCRIPT config generate -l debug\` for more information."
+            exit 1
+        fi
     fi
-fi
 
-orig_vmargs_path="$VMARGS_PATH.orig"
-if [ $RELX_REPLACE_OS_VARS ]; then
-    #Make sure we don't break dev mode by keeping the symbolic link to 
-    #the user's vm.args
-    if [ ! -L "$orig_vmargs_path" ]; then
-       #we're in copy mode, rename the vm.args file to vm.args.orig
-       mv "$VMARGS_PATH" "$orig_vmargs_path"
+    if ! relx_nodetool chkconfig $CONFIG_ARGS; then
+        echoerr "Error reading $CONFIG_ARGS"
+        exit 1
     fi
-
-    awk '{while(match($0,"[$]{[^}]*}")) {var=substr($0,RSTART+2,RLENGTH -3);gsub("[$]{"var"}",ENVIRON[var])}}1' < "$orig_vmargs_path" > "$VMARGS_PATH"
- else
-    #We don't need to replace env. vars, just rename the
-    #symlink vm.args.orig to vm.args, and keep it as a
-    #symlink.
-    if [ -L "$orig_vmargs_path" ]; then
-       mv "$orig_vmargs_path" "$VMARGS_PATH" 
-    fi
-fi
+    echo "config is OK"
+    echo $CONFIG_ARGS
+}
 
 # Make sure log directory exists
 mkdir -p "$RUNNER_LOG_DIR"
 
-# Use $CWD/sys.config if exists, otherwise releases/VSN/sys.config
-if [ -z "$RELX_CONFIG_PATH" ]; then
-    if [ -f "$RELEASE_ROOT_DIR/sys.config" ]; then
-        RELX_CONFIG_PATH="$RELEASE_ROOT_DIR/sys.config"
-    else
-        RELX_CONFIG_PATH="$REL_DIR/sys.config"
-    fi
-fi
-
-orig_relx_config_path="$RELX_CONFIG_PATH.orig"
-if [ $RELX_REPLACE_OS_VARS ]; then
-    #Make sure we don't break dev mode by keeping the symbolic link to 
-    #the user's sys.config
-    if [ ! -L "$orig_relx_config_path" ]; then
-       #We're in copy mode, rename sys.config to sys.config.orig
-       mv "$RELX_CONFIG_PATH" "$orig_relx_config_path"
-    fi
-
-    awk '{while(match($0,"[$]{[^}]*}")) {var=substr($0,RSTART+2,RLENGTH -3);gsub("[$]{"var"}",ENVIRON[var])}}1' < "$orig_relx_config_path" > "$RELX_CONFIG_PATH"
- else
-    #We don't need to replace env. vars, just rename the
-    #symlink sys.config.orig to sys.config. Keep it as 
-    #a symlink.
-    if [ -L "$orig_relx_config_path" ]; then
-       mv "$orig_relx_config_path"  "$RELX_CONFIG_PATH"
-    fi
-fi
-
 # Extract the target node name from node.args
-NAME_ARG=$(egrep '^-s?name' "$VMARGS_PATH" || true)
+# NAME_ARG=`egrep '^\-name' $RUNNER_ETC_DIR/vm.args 2> /dev/null`
 if [ -z "$NAME_ARG" ]; then
-    echo "vm.args needs to have either -name or -sname parameter."
-    exit 1
+    NODENAME=`egrep '^[ \t]*node.name[ \t]*=[ \t]*' $RUNNER_ETC_DIR/emq.conf 2> /dev/null | tail -1 | cut -d = -f 2`
+    if [ -z "$NODENAME" ]; then
+        echoerr "vm.args needs to have a -name parameter."
+        echoerr "  -sname is not supported."
+        exit 1
+    else
+        NAME_ARG="-name ${NODENAME# *}"
+    fi
 fi
 
 # Extract the name type and name from the NAME_ARG for REMSH
@@ -174,10 +168,15 @@ NAME="$(echo "$NAME_ARG" | awk '{print $2}')"
 PIPE_DIR="${PIPE_DIR:-/tmp/erl_pipes/$NAME/}"
 
 # Extract the target cookie
-COOKIE_ARG="$(grep '^-setcookie' "$VMARGS_PATH" || true)"
+# COOKIE_ARG=`grep '^\-setcookie' $RUNNER_ETC_DIR/vm.args 2> /dev/null`
 if [ -z "$COOKIE_ARG" ]; then
-    echo "vm.args needs to have a -setcookie parameter."
-    exit 1
+    COOKIE=`egrep '^[ \t]*node.cookie[ \t]*=[ \t]*' $RUNNER_ETC_DIR/emq.conf 2> /dev/null | tail -1 | cut -d = -f 2`
+    if [ -z "$COOKIE" ]; then
+        echoerr "vm.args needs to have a -setcookie parameter."
+        exit 1
+    else
+        COOKIE_ARG="-setcookie $COOKIE"
+    fi
 fi
 
 # Extract cookie name from COOKIE_ARG
@@ -372,6 +371,10 @@ case "$1" in
                 shift
                 ;;
         esac
+
+        #generate app.config and vm.args
+        generate_config
+
         # Setup beam-required vars
         EMU="beam"
         PROGNAME="${0#*/}"
@@ -386,9 +389,8 @@ case "$1" in
         # Build it here because this command will be used for logging.
         set -- "$BINDIR/erlexec" -boot "$BOOTFILE" -mode "$CODE_LOADING_MODE" \
             -boot_var ERTS_LIB_DIR "$ERTS_LIB_DIR" \
-            -config "$RELX_CONFIG_PATH" \
             -mnesia dir "\"${MNESIA_DATA_DIR}\"" \
-            -args_file "$VMARGS_PATH"
+            $CONFIG_ARGS
 
         # Dump environment info for logging purposes
         echo "Exec: $@" -- ${1+$ARGS}
